
# ─────────────────────────────────────────
# CAUSAS NTC 5736:2009 (reutilizable)
# ─────────────────────────────────────────
CAUSAS_NTC = [
    "500 — Uso anormal",
    "510 — Respuesta fisiológica anormal o inesperada",
    "520 — Falla en la alarma",
    "530 — Uso de material biológico",
    "540 — Calibración incorrecta",
    "550 — Hardware del computador",
    "560 — Contaminación durante la producción",
    "570 — Contaminación postproducción",
    "580 — Diseño inadecuado",
    "590 — Desconexión imprevista",
    "600 — Componente eléctrico defectuoso",
    "610 — Circuito eléctrico",
    "620 — Contacto eléctrico defectuoso",
    "630 — Interferencia Electromagnética (IEM)",
    "640 — Fecha de expiración vencida",
    "650 — Falso negativo",
    "660 — Falso positivo",
    "670 — Resultado falso de la prueba",
    "680 — Falla en dispositivo implantable",
    "690 — Ambiente inapropiado",
    "700 — Incompatibilidad entre dispositivos",
    "710 — Instrucciones para uso / etiquetado inadecuados",
    "720 — Escape / falla en sellado",
    "730 — Mantenimiento inadecuado",
    "740 — Falla en fabricación",
    "750 — Material de durabilidad limitada",
    "760 — Componentes mecánicos",
    "770 — Condiciones no higiénicas",
    "780 — No relacionado con el dispositivo",
    "790 — Otros",
    "800 — Empaque inadecuado",
    "810 — Anatomía / fisiología del paciente",
    "820 — Condición del paciente",
    "830 — Fuente de energía deficiente",
    "840 — Falla en medidas de protección",
    "850 — Aseguramiento de calidad en la institución",
    "860 — Radiación",
    "870 — Software inadecuado",
    "880 — Esterilización / desinfección / limpieza inadecuada",
    "890 — Condiciones de almacenamiento inapropiadas",
    "900 — Alteración, falsificación o sabotaje",
    "910 — Entrenamiento inadecuado",
    "920 — Transporte y entrega",
    "930 — Sin identificar",
    "940 — Capacidad de uso",
    "950 — Error de uso",
    "960 — Desgaste",
]

